#!/bin/env bash

WINDOW=$(wmctrl -lp | dmenu -i -l 20 -p 'Select window: ' | awk '{print $1}')
DESTINATION=$(wmctrl -d | dmenu -i -l 20 -p 'Destination Desktop: ' | awk '{print $1}')
if [[ "$WINDOW" == "" ]]; then
    exit 0
elif [[ "$DESTINATION" == "" ]]; then
    exit 0
else
    wmctrl -ir "$WINDOW" -t "$DESTINATION"
    exit 0
fi
