#!/bin/env bash

MD_NOTE="$HOME/Documents/Finance/$(date +%Y-%m).md"
NOTE="$HOME/Documents/Finance/buffer-$(date +%Y-%m)"
PDF_NOTE="$HOME/Documents/Finance/pdf/$(date +%Y-%m).pdf"
PDF_DIR="$HOME/Documents/Finance/pdf"
PIE_CHART="$HOME/Documents/Finance/plot/pie.png"

createMarkDown () {
    echo -e "---\ntitle: Financial Report\nauthor: André Rønning\ndate: $(date +%B-%Y)\ngeometry: margin=3cm\n---\n\n| date | Description | in | out | Category |\n|------|-------------|----:|:-----|----------|" > $MD_NOTE
    readarray -t array < $NOTE
    for line in ${array[@]}
    do
        if [[ "$line" != " " ]]; then
            date=$(echo "$line"  | awk -F ":" '{print $1}')
            money=$(echo "$line" | awk -F ":" '{print $2}')
            desc=$(echo "$line"  | awk -F ":" '{print $3}')
            mark=$(echo "$line"  | awk -F ":" '{print $4}')
            
            if [[ "$mark" == "b" ]]; then
                bill=$(( bill + money ))
                category="Bills"
            elif [[ "$mark" == "f" ]]; then
                food=$(( food + money ))
                category="Food"
            elif [[ "$mark" == "c" ]]; then
                clothes=$(( clothes + money ))
                category="Clothes"
            elif [[ "$mark" == "l" ]]; then
                luxoury=$(( luxoury + money ))
                category="Luxoury"
            elif [[ "$mark" == "s" ]]; then
                subscriptions=$(( subscriptions + money ))
                category="Subscriptions"
            elif [[ "$mark" == "i" ]]; then
                income=$(( income + money ))
                category="Income"
            elif [[ "$mark" == "t" ]]; then
                tobacco=$(( tobacco + money ))
                category="Tobacco"
            fi

            if [[ $money -gt 0 ]]; then
                totalIn=$(( totalIn + money ))
                echo "|$date|$desc|$money| |$category|" >> $MD_NOTE
            elif [[ $money -le 0 ]]; then
                totalOut=$(( totalOut + money ))
                echo "|$date|$desc| |$money|$category|" >> $MD_NOTE
            fi
        fi
    done

    balance=$(( totalIn + totalOut ))
    echo -e "\n\n| Total in | Total out | Balance |" >> $MD_NOTE
    echo "|----------|-----------|---------|" >> $MD_NOTE
    echo -e "| $totalIn | $totalOut | $balance |\n\n" >> $MD_NOTE
    
    [[ ! "$bill" ]] && bill=0
    [[ ! "$clothes" ]] && clothes=0
    [[ ! "$food" ]] && food=0
    [[ ! "$luxoury" ]] && luxoury=0
    [[ ! "$subscriptions" ]] && subscriptions=0
    [[ ! "$tobacco" ]] && tobacco=0

    /usr/bin/python $HOME/Scripts/Programs/assorted-scripts/create_financial_plot.py -b $bill -c $clothes -f $food -l $luxoury -s $subscriptions -t $tobacco
    echo "![pie-chart]($PIE_CHART)" >> $MD_NOTE

    pandoc -o $PDF_NOTE $MD_NOTE &
}

if [[ "$1" == "v" ]]; then
    PDF_LIST=($PDF_DIR/*)
    PDF=$(printf '%s\n' "${PDF_LIST[@]}" | awk -F "/" '{print $NF}' | dmenu -i -c -l 20 -p "PDF summary: ")
    [[ ! "$PDF" ]] && exit 1 || zathura "$PDF_DIR/$PDF"

else
    [[ ! -f $MD_NOTE ]] && touch $NOTE
    [[ ! -f $MD_NOTE ]] && ( echo -e "---\ntitle: Financial Report\nauthor: André Rønning\ndate: $(date +%B-%Y)\ngeometry: margin=3cm\n---\n\n" > $MD_NOTE)
    [[ ! -f $PDF_NOTE ]] && (touch $PDF_NOTE)

    alacritty -t Notes -e nvim -c "norm Go $(date +%Y-%m-%d:)" \
         -c "norm 0x" \
         -c "norm A" \
         -c "norm zz" \
         -c "startinsert" $NOTE
    createMarkDown    
fi

# Example for logging expence or deposits
# The date is inserted for you
# date:amount:reason:category
# 2021-06-24:4000:Sold my body:i
# 2021-06-24:-4000:Icecream:l

# Categories
# b=bills, f=food, c=clothes, l=luxoury, s=subscriptions, i=income, t=tobacco
