#!/bin/env bash

OS=$( lsb_release -a | awk 'NR==2 {print $3 " \"Just keep rolling\"" }' )
KERNEL=$( uname -r )
PACKAGES_INSTALLED=$( pacman -Q | wc -l )
SHELL_VERSION=$( "$SHELL" --version | awk '{print $1 " " $2}')
WINDOW_MANAGER=$( echo $DESKTOP_SESSION )
TERMINAL_EMULATOR=$( echo $TERM )
CPU=$( bat /proc/cpuinfo | awk 'NR==5 {print $4 " " $5 " " $6}' )
CPU_THREADS=$( bat /proc/cpuinfo | awk 'NR==11 {print $3}' )
CPU_FREQUENCY=$( bat /proc/cpuinfo | awk 'NR==8 {print $4}' )
GPU="$(lspci -mm | awk -F '\"|\" \"|\\(' \
                            '/"Display|"3D|"VGA/ {a[$0] = $1 " " $3 " " $4}
                            END {for(i in a) {if(!seen[a[i]]++) print a[i]}}' | awk '{print $2 " " $3 " " $4 " " $5 " " $6 " " $7}')"
MEM_TOTAL=$( free -mh | awk 'NR==2 {print $2}' )
MEM_USED=$( free -mh | awk 'NR==2 {print $3}' )

MOTHERBOARD_VENDOR=$( cat /sys/devices/virtual/dmi/id/board_vendor | awk '{print $1}')
MOTHERBOARD_NAME=$( cat /sys/devices/virtual/dmi/id/board_name )
MOTHERBOARD_REV=$( cat /sys/devices/virtual/dmi/id/board_version )

declare -a INFO=(
"OS:                    $OS"
"WM:                    $WINDOW_MANAGER"
"Kernel:                $KERNEL"
"shell:                 $SHELL_VERSION"
"terminal:              $TERMINAL_EMULATOR"
"Installed Packages:    $PACKAGES_INSTALLED"
"cpu:                   $CPU ($CPU_THREADS) @ $CPU_FREQUENCY MHz"
"gpu:                   $GPU"
"memory:                $MEM_USED / $MEM_TOTAL"
"Motherboard            $MOTHERBOARD_VENDOR $MOTHERBOARD_NAME $MOTHERBOARD_REV"
"Filesystem             -->"
"Processes              --->"
)

CHOICE=$(printf '%s\n' "${INFO[@]}" | dmenu -i -l 20 -p 'test' | awk '{print $2}')
[[ "$CHOICE" = "-->" ]] && ( df -Ph | dmenu -i -l 20 -p 'File System: ' )
[[ "$CHOICE" = "--->" ]] && ( dmkill )
[[ "$CHOICE" ]] && exit || exit
