#!/bin/env bash
# using dmenu to list all open windows
# select the window you want and it will be sent to your current desktop, and gain focus

PROGRAM_PID=$(wmctrl -lp | dmenu -i -l 20 -p 'Active Windows: ' | awk '{print $1}')
[[ ! "$PROGRAM_PID" == "" ]] && ( wmctrl -iR "$PROGRAM_PID"; exit 0 ) || ( exit 0 )
