#!/bin/env bash
# Oneliner for use as alias
# man -k . | dmenu -c -i -l 20 -p 'Man pages: ' | awk '{print $1}' | xargs -r man -Tpdf | zathura -

# Script for keybinding in ex sxhkd
MAN=$(man -k . | dmenu -c -i -l 20 -p 'Man pages: ' | awk '{print $1}' )
[[ ! "$MAN" == "" ]] && ( man -Tpdf $MAN | zathura - ) || ( exit 0 )
