#!/bin/env bash

lang="en"
browser="brave"

wikidir="/usr/share/doc/arch-wiki/html/$lang/"
wikidocs="$(find ${wikidir} -iname "*.html")"

main() {
    choice=$(printf '%s\n' "${wikidocs[@]}" | \
           cut -d '/' -f8- | \
           sed -e 's/_/ /g' -e 's/.html//g' | \
           sort | \
           dmenu -i -l 20 -c -p 'Arch Wiki Docs: ' "$@") || exit 1

    if [ "$choice" ]; then
        article=$(printf '%s\n' "${wikidir}${choice}.html" | sed 's/ /_/g')
        $browser "$article"
    else
        echo "Program terminated." && exit 0
    fi
}
main
