#!/bin/sh

MD_NOTE="$HOME/Documents/Diary/$(date +%Y-%m).md"
PDF_NOTE="$HOME/Documents/Diary/pdf/$(date +%Y-%m).pdf"
PDF_DIR="$HOME/Documents/Diary/pdf"

if [[ "$1" == "v" ]]; then
    PDF_LIST=($PDF_DIR/*)
    PDF=$(printf '%s\n' "${PDF_LIST[@]}" | awk -F "/" '{print $NF}' | dmenu -i -c -l 20 -p "PDF diary: ")
    [[ ! "$PDF" ]] && exit 1 || zathura "$PDF_DIR/$PDF"

else
    [[ ! -f $MD_NOTE ]] && ( echo -e "---\ntitle: Diary\nauthor: André Rønning\ndate: $(date +%B-%Y)\ngeometry: margin=3cm\n---" > $MD_NOTE)
    [[ ! -f $PDF_NOTE ]] && ( touch $PDF_NOTE)

    alacritty -t Notes -e nvim -c "norm G2o" \
         -c "norm Go## $(date +%H:%M:%S)" \
         -c "norm Go" \
         -c "norm zz" $MD_NOTE
    
    pandoc -o $PDF_NOTE $MD_NOTE &
fi

# I make sure that ~/.local/bin/ or ~/.local/share/ is in my path
# and symlink it to one of these locations as n
# Then i add {'wname': 'Notes'}, to my floating_rules in the Qtile config
# now I can add it to a keybinding in sxhkd or call it from the terminal
# and open up a floating window, in vim, to take notes in using markdown
# and each new day a new file is created using that days date in the filename
# also each entry gets timestamped automatically inside the document
# I use the keybinding super n to open it in vim, and super shift n to view the pdf version of it
