#!/bin/env bash
shopt -s nullglob
WEATHERPATH="$HOME/Documents/vær"
YR_PDF=($WEATHERPATH/*)
DATE="$(date +%Y-%m-%d)"
GEO_LOCATION=$(cat "$HOME/Documents/yr-location")

if [[ "$1" == "v" ]]; then
    SELECTION=$(printf '%s\n' "${YR_PDF[@]}" | awk -F "/" '{print $NF}' | dmenu -i -c -l 20 -p "Weather files: ")
    [[ ! "$SELECTION" ]] && exit 1
    devour zathura "$WEATHERPATH/$SELECTION"
elif [[ ! -f "$WEATHERPATH/$DATE-forecast.pdf" ]]; then
    cd $HOME/Documents/vær
    wget -O "$DATE-forecast.pdf" "$GEO_LOCATION"
    devour zathura "$WEATHERPATH/$DATE-forecast.pdf"
else
    devour zathura "$WEATHERPATH/$DATE-forecast.pdf"
fi
