#!/bin/env bash

echo -e "qtile-config\t$HOME/.config/qtile/config.py"
echo -e "qtile-keys\t$HOME/.config/qtile/keybindings.py"
echo -e "qtile-colors\t$HOME/.config/qtile/colorprofile.py"
echo -e "qtile-autostart\t$HOME/.config/qtile/scripts/autostart.sh"
echo -e "zshrc\t$HOME/.config/zsh/.zshrc"
echo -e "sxhkd\t$HOME/.config/sxhkd/sxhkdrc"
echo -e "nvim\t$HOME/.config/nvim/init.vim"
echo -e "ranger-rc\t$HOME/.config/ranger/rc.conf"
echo -e "ranger-rifle\t$HOME/.config/ranger/rifle.conf"
echo -e "ranger-scope\t$HOME/.config/ranger/scope.sh"
echo -e "qutebrowser\t$HOME/.config/qutebrowser/config.py"
echo -e "polybar\t$HOME/.config/polybar/config"
echo -e "alacritty\t$HOME/.config/alacritty/alacritty.yml"
echo -e "picom\t$HOME/.config/picom/picom.conf"

